### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by tterrag1098** [lairtonb/serimongo#20]
This project looks useful, but it is unusable for a lot of people (including me) without a declared software license.

**Comment by lairtonb** [comment]
I agree, sorry for that.  Used Apache 2.0, same license as  [serilog-sinks-mongodb](https://github.com/serilog/serilog-sinks-mongodb).

This project was always more like a backup. As such, I never gave it much attention. If you have any suggestions, please let me know. If there is interest and I find time, I may resume work on it.
